name: Build and Deploy

on:
  workflow_dispatch:
    inputs:
      branch_name:
        type: choice
        required: true
        description: Branch Name
        options: 
        - master
        - staging
        - multi
        
      environment: 
        type: choice
        required: true
        description: Environment Name
        options: 
        - master
        - staging
        - multi
        
# env:
#     AZURE_CONTAINER_REGISTRY: ${{ AWS_ACCESS_KEY_ID }}
#     IMAGE_PULL_SECRET_NAME: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#     CLUSTER_NAME: ${{ secrets.KUBE_CONFIG }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - uses: actions/checkout@v2                
    
      - name: 'Run on master branch'
        if: ${{ github.event.inputs.branch_name == 'master' }}
        run: |
         echo "Action executed on master branch"
      
      - name: 'Run on staging branch'
        if: ${{ github.event.inputs.branch_name == 'staging' }}
        run: |
         echo "Action executed on staging branch"          
         echo "AZURE_CONTAINER_REGISTRY: $AWS_ACCESS_KEY_ID"
         
      - name: 'Run on multi branch'
        if: ${{ github.event.inputs.branch_name == 'multi' }}
        run: |
         echo "Action executed on multi branch"
         
      - name: 'Executing the common code'
        run: |
         echo "Executing the common steps"
         
         
