name: Build and Deploy

on:
  workflow_dispatch:
    inputs:
      branch_name:
        type: choice
        required: true
        description: Branch Name
        options: 
        - master
        - staging
        - multi

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2                
    
      - name: 'Run on master branch'
        if: ${{ github.event.inputs.branch_name == 'refs/heads/master' }}
        run: |
         echo "Action executed on master branch"
      
      - name: 'Run on staging branch'
        if: ${{ github.event.inputs.branch_name == 'refs/heads/staging' }}
        run: |
         echo "Action executed on staging branch"        
         
      - name: 'Run on multi branch'
        if: ${{ github.event.inputs.branch_name == 'refs/heads/multi' }}
        run: |
         echo "Action executed on multi branch"
